import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const scriptDirectory = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(scriptDirectory, "..");
const manifestPath = path.join(projectRoot, "proto", "upstream.json");
const manifest = JSON.parse(readFileSync(manifestPath, "utf8"));
const args = parseArguments(process.argv.slice(2));

if (args.check && args.ref) {
  throw new Error("--ref cannot be combined with --check");
}

const requestedRevision = args.ref || manifest.commit;
const source = openSourceRepository(args.source, requestedRevision);

try {
  const resolvedCommit = git(source.path, [
    "rev-parse",
    `${source.revision}^{commit}`,
  ]).trim();
  const wireVersion = readWireVersion(source.path, resolvedCommit);
  const schemaFiles = git(source.path, [
    "ls-tree",
    "--name-only",
    `${resolvedCommit}:${manifest.schemaRoot}`,
  ])
    .split("\n")
    .filter((filename) => filename.endsWith(".proto"))
    .sort();
  const schemas = new Map(
    schemaFiles.map((filename) => [
      filename,
      normalizeImports(
        git(source.path, [
          "show",
          `${resolvedCommit}:${manifest.schemaRoot}/${filename}`,
        ]),
      ),
    ]),
  );

  if (args.check) {
    checkSnapshot({ resolvedCommit, schemas, wireVersion });
  } else {
    writeSnapshot({
      ref: args.ref || manifest.ref,
      resolvedCommit,
      schemas,
      wireVersion,
    });
  }
} finally {
  source.cleanup();
}

function parseArguments(values) {
  const parsed = { check: false, ref: null, source: null };
  for (let index = 0; index < values.length; index += 1) {
    const value = values[index];
    if (value === "--check") {
      parsed.check = true;
    } else if (value === "--ref" || value === "--source") {
      const argument = values[index + 1];
      if (!argument) {
        throw new Error(`${value} requires a value`);
      }
      parsed[value.slice(2)] = argument;
      index += 1;
    } else {
      throw new Error(`Unknown argument: ${value}`);
    }
  }
  return parsed;
}

function openSourceRepository(localSource, revision) {
  if (localSource) {
    return {
      path: path.resolve(projectRoot, localSource),
      revision,
      cleanup() {},
    };
  }

  const temporaryRepository = mkdtempSync(
    path.join(tmpdir(), "compas-pb-schema-"),
  );
  git(temporaryRepository, ["init", "--quiet"]);
  git(temporaryRepository, ["remote", "add", "origin", manifest.repository]);
  git(temporaryRepository, [
    "fetch",
    "--quiet",
    "--depth=1",
    "origin",
    revision,
  ]);
  return {
    path: temporaryRepository,
    revision: "FETCH_HEAD",
    cleanup() {
      rmSync(temporaryRepository, { recursive: true, force: true });
    },
  };
}

function git(cwd, arguments_) {
  return execFileSync("git", arguments_, { cwd, encoding: "utf8" });
}

function readWireVersion(repositoryPath, commit) {
  const initFile = git(repositoryPath, [
    "show",
    `${commit}:src/compas_pb/__init__.py`,
  ]);
  const match = initFile.match(/^__version__\s*=\s*["']([^"']+)["']/m);
  if (!match) {
    throw new Error("Could not find compas_pb.__version__ in the selected ref");
  }
  return match[1];
}

function normalizeImports(contents) {
  return contents.replaceAll("compas_pb/generated/", "compas_pb/data/");
}

function expectedVersionModule(wireVersion, commit) {
  return `// Generated by scripts/proto-sync.mjs from compas_pb ${commit}.\nexport const COMPAS_PB_VERSION = "${wireVersion}";\n`;
}

function checkSnapshot({ resolvedCommit, schemas, wireVersion }) {
  const mismatches = [];
  if (resolvedCommit !== manifest.commit) {
    mismatches.push(
      `manifest commit ${manifest.commit} does not resolve to ${resolvedCommit}`,
    );
  }
  if (wireVersion !== manifest.wireVersion) {
    mismatches.push(
      `manifest wire version ${manifest.wireVersion} does not match ${wireVersion}`,
    );
  }
  if (
    JSON.stringify([...schemas.keys()]) !==
    JSON.stringify([...manifest.files].sort())
  ) {
    mismatches.push("manifest schema file list differs from upstream");
  }
  for (const [filename, contents] of schemas) {
    const snapshotPath = path.join(
      projectRoot,
      "proto",
      "compas_pb",
      "data",
      filename,
    );
    if (readFileSync(snapshotPath, "utf8") !== contents) {
      mismatches.push(`${filename} differs from ${manifest.commit}`);
    }
  }
  const versionPath = path.join(
    projectRoot,
    "src",
    "generated",
    "compas_pb",
    "version.ts",
  );
  if (
    readFileSync(versionPath, "utf8") !==
    expectedVersionModule(wireVersion, resolvedCommit)
  ) {
    mismatches.push("generated wire-version module is stale");
  }

  if (mismatches.length > 0) {
    throw new Error(
      `Protobuf snapshot check failed:\n- ${mismatches.join("\n- ")}`,
    );
  }
  console.log(
    `Protobuf snapshot matches compas_pb ${manifest.ref} (${manifest.commit}).`,
  );
}

function writeSnapshot({ ref, resolvedCommit, schemas, wireVersion }) {
  for (const oldFilename of manifest.files) {
    if (!schemas.has(oldFilename)) {
      rmSync(path.join(projectRoot, "proto", "compas_pb", "data", oldFilename));
    }
  }
  for (const [filename, contents] of schemas) {
    writeFileSync(
      path.join(projectRoot, "proto", "compas_pb", "data", filename),
      contents,
    );
  }

  const nextManifest = {
    ...manifest,
    ref,
    commit: resolvedCommit,
    wireVersion,
    files: [...schemas.keys()],
  };
  writeFileSync(manifestPath, formatManifest(nextManifest));
  writeFileSync(
    path.join(projectRoot, "src", "generated", "compas_pb", "version.ts"),
    expectedVersionModule(wireVersion, resolvedCommit),
  );
  console.log(
    `Synced compas_pb ${ref} (${resolvedCommit}) wire version ${wireVersion}.`,
  );
}

function formatManifest(value) {
  return `${JSON.stringify(value, null, 2).replace(
    /"files": \[\n\s+([^\]]+)\n\s+\]/,
    (_, files) =>
      `"files": [${files
        .split(",\n")
        .map((file) => file.trim())
        .join(", ")}]`,
  )}\n`;
}
